name: eggd800
channels:
  - conda-forge
dependencies:
  - click
  - git
  - ipython
  - jupyter
  - matplotlib
  - pandas
  - pip
  - python
  - python-sounddevice
  - pyyaml
  - scipy
  - pip:
    - git+https://github.com/rsprouse/eggd800
