name: amznas
channels:
  - conda-forge
dependencies:
  - click
  - git
  - ipython
  - jupyter
  - matplotlib=3.4
  - pandas=1.3
  - pip
  - python=3.9
  - python-sounddevice
  - pyyaml=5.4
  - scipy
  - pip:
    - git+https://github.com/rsprouse/eggd800
    - git+https://github.com/rsprouse/phonlab
