#!/usr/bin/env python

# Command line utility for Amazonian Nasality project

# TODO: check --lx param
# TODO: try to prevent lx recording when not requested

try:
    import os
    import re
    import glob
    import subprocess
    import yaml
    import numpy as np
    import pandas as pd
    from pathlib import Path
    from datetime import datetime as dt
    import scipy.io.wavfile
    import wave
    from eggd800.eggdisp import egg_display
    import click
    from phonlab.utils import dir2df, get_timestamp_now
except:
    print()
    print('Could not import required modules.')
    print('Try to load them with:')
    print('    conda activate amznas')
    print()
    exit(0)

try:
    datadir = os.path.join(os.environ['USERPROFILE'], 'Desktop', 'eggd800')
except KeyError:
    datadir = os.path.join(os.environ['HOME'], 'Desktop', 'eggd800')

wavpat = re.compile(
    '(?P<lang>[^_]+)_(?P<spkr>[^_]+)_(?P<researcher>[^_]+)_(?P<tstamp>[^_]+)_(?P<item>.+)_(?P<rep>\d+)\.wav$'
)

class EggCfg(object):
    '''A config for the project.'''
    def __init__(self, datadir=datadir, ymlname='amznas.yml'):
        super(EggCfg, self).__init__()
        self.datadir = datadir
        self.cfgfile = os.path.join(datadir, ymlname)
        self._lang = None
        self._researcher = None
        try:
            with open(self.cfgfile, 'r') as fh:
                cfg = yaml.safe_load(fh)
            for fld in ('lang', 'researcher'):
                try:
                    assert(re.match('^[a-zA-Z]{3}$', cfg[fld]))
                    setattr(self, f'_{fld}', cfg[fld])
                except AssertionError:
                    msg = f'''
The '{fld}' value must be a 3-character code.
You must correct the value in {self.cfgfile} before continuing.
'''
                    raise RuntimeError(msg)
                except KeyError:
                    print(f'No config default for {fld}.')
        except FileNotFoundError:
            pass

    def prompt_for_save(self, fld, val):
        msg = f'''
You have changed the configuration to:

lang: {val if fld == 'lang' else self.lang}
researcher: {val if fld == 'researcher' else self.researcher}

Save this configuration for next time? (y/n)
'''
        r = input(msg).strip().lower()
        if r == 'y':
            return True
        elif r == 'n':
            return False
        else:
            return self.prompt_for_save(fld, val)

    def save(self):
        with open(self.cfgfile, 'w') as fh:
            yaml.dump(
                {'lang': self.lang, 'researcher': self.researcher},
                fh,
                default_flow_style=False
            )

    @property
    def lang(self):
        return self._lang

    @lang.setter
    def lang(self, val):
        try:
            assert(re.match('^[a-zA-Z]{3}$', val))
        except AssertionError:
            msg = 'Lang identifier must be a 3-character ISO code.'
            raise RuntimeError(msg)
        if self._lang != val:
            do_save = self.prompt_for_save('lang', val)
        self._lang = val
        if do_save is True:
            self.save()
            print(f'Saved configuration in {self.cfgfile}.')
        else:
            print('Configuration change not saved.')

    @property
    def researcher(self):
        return self._researcher

    @researcher.setter
    def researcher(self, val):
        try:
            assert(re.match('^[a-zA-Z]{3}$', val))
        except AssertionError:
            msg = 'Researcher identifier must be a 3-character code.'
            raise RuntimeError(msg)
        if self._researcher != val:
            do_save = prompt_for_save('researcher', val)
        self._researcher = val
        if do_save is True:
            self.save()
            print(f'Saved configuration in {self.cfgfile}.')
        else:
            print('Configuration change not saved.')

def validate_ident(ctx, param, value):
    if value is None and param.name in ('researcher', 'lang'):
        raise click.BadParameter(f'`--{param.name} XXX` must be included as a command parameter.')
    try:
        assert(re.match('^[a-zA-Z]{3}$', value))
    except AssertionError:
        raise click.BadParameter(f'Identifier "{value}" must be exactly three characters')
    return value.lower()

def next_token(sessdir, lang, spkr, researcher, tstamp, item):
    '''Get the number of the next token for a .wav acquisition file, as a str.'''
    date = tstamp.split('T')[0]
    token = '0'
    # 1. Windows filesystems are case-insensitive. If the project's
    # transcription system distinguishes phone by case, e.g. s vs. S, then it
    # is not possible to distinguish items that differ only in case of one
    # or more characters. As a result we use re.IGNORECASE when matching
    # filenames, and the token count conflates these items.
    #
    # 2. Only the date portion of the timestamp is important
    # for determining the token number, and the time portion is ignored.
    fnpat = re.compile(
        f'^{lang}_{spkr}_{researcher}_{date}[^_]*_{item}_(?P<token>\d+)\.wav$',
        re.IGNORECASE
    )
    df = dir2df(sessdir, fnpat=fnpat)
    if len(df) > 0:
        token = df['token'].astype(int).max() + 1
    return str(token)

def get_fpath(sessdir, lang, spkr, researcher, tstamp, item, token=None):
    '''Construct and return filepath for acquisition .wav file.'''
    if token == None or token < 0:
        nexttok = next_token(sessdir, lang, spkr, researcher, tstamp, item)
        token = int(nexttok) if token == None else int(nexttok)+token
    fname = f'{lang}_{spkr}_{researcher}_{tstamp}_{item}_{token}'
    return (
        token,
        os.path.join(sessdir, f'{fname}.wav'),
        os.path.join(sessdir, f'{fname}.ini')
    )

def find_wav(sessdir, lang, spkr, researcher, date, item, token):
    '''Find existing acquisition .wav file.'''
    fre = f'{lang}_{spkr}_{researcher}_{date}T??????_{item}_{token}.wav'
    return (glob.glob(os.path.join(sessdir, fre)) , fre)

def boolstr(b):
    '''
    Return a boolean as a '1' (True) or '0' (False).
    '''
    return '1' if b is True else '0'

def get_ini(flow, pressure, lx, spkr, item, token, utt, device):
    '''Return string rep of ini file.'''
    if device == '1':
    # TODO: proper channel selection for revision a device
        chansel = '00001111'
        p2ctrl = '\nP2 = 1\n'
    else:
    # '00000011' = sp + lx
    # '00101001' = sp + oralf + nasalf
    # '00111001' = sp + oralf + oralp + nasalf
    # '00101011' = sp + lx + oralf + nasalf
    # '00111011' = sp + lx + oralf + oralp + nasalf
        chansel = f'00{boolstr(flow)}{boolstr(pressure)}{boolstr(flow)}0{boolstr(lx)}1'
        p2ctrl = 'P2 = 1\n' if pressure is True else ''
    print(f'chansel: {chansel}, lxstr {boolstr(lx)}')
    return f'''
[Device]
ChannelSelection = {chansel}
{p2ctrl}Lx = {boolstr(lx)}
SampleRate = 120000
MICGAIN = 4
LXGAIN = 1
NXGAIN = 4
NXPREAMP = 0

[Subject]
ID = {spkr}
Surname = 
Firstname = 
UtteranceID = {item}_{token}
Utterance = {utt}
'''

def run_acq(fpath, inifile, seconds):
    '''Run an acquisition.'''
    args = [
        os.path.normpath('C:/bin/Recorder.exe'),
        '-ini', inifile,
        '-of', fpath
    ]
    msg = 'Acquiring. Press Ctrl-C to stop.'
    if seconds is not None:
        args.extend(['-tm', seconds])
        msg = f'Acquiring for {seconds} seconds.'
    try:
        subprocess.run(args)
    except KeyboardInterrupt:
        pass

def stash_chanmeans(wav, chan, token, sessdir, lang, spkr, researcher, today):
    '''
    Store channel means in a yaml file in the session directory.
    '''
    yamlfile = os.path.join(
        sessdir,
        f'{lang}_{spkr}_{today}_session.yaml'
    )
    try:
        with open(yamlfile, 'r') as fh:
            sessmd = yaml.safe_load(fh)
    except FileNotFoundError:
        sessmd = {
            'session': {
                'spkr': spkr,
                'lang': lang,
            },
            'acq': []
        }
    (rate, data) = scipy.io.wavfile.read(wav)
    cmeans = data.mean(axis=0)
    chanmeans = []
    for cidx, c in enumerate(chan):
        label = 'no_label' if c is None or c == '' else c
        chanmeans.append({
                'idx': cidx,
                'type': label,
                # If we don't cast to float yaml.dump exports the value
                # as a numpy object instead of a simple float.
                'mean': float(cmeans[cidx]),
                'status': 'automean'
            })
    sessmd['acq'].append({
        'item': '_zero_',
        'token': token,
        'researcher': researcher,
        'fname': os.path.basename(wav),
        'channels': chanmeans
    })
    with open(yamlfile, 'w') as fh:
        yaml.dump(sessmd, fh, sort_keys=False)

def load_sess_yaml(sessdir, lang, spkr, today):
    '''
    Load session metadata from yaml file.
    '''
    yamlfile = os.path.join(
        sessdir,
        f'{lang}_{spkr}_{today}_session.yaml'
    )
    try:
        with open(yamlfile, 'r') as fh:
            sessmd = yaml.safe_load(fh)
    except FileNotFoundError:
        sessmd = {
            'session': {
                'spkr': spkr,
                'lang': lang,
            },
            'acq': []
        }
    return sessmd

def wav_display(wav, chan, cutoff, lporder, chanmeans):
    (rate, data) = scipy.io.wavfile.read(wav)
    if len(chanmeans) == data.shape[1]:
        data -= np.array(chanmeans).astype(data.dtype)
    r = egg_display(
        data,
        rate,
        chan=chan,
        del_btn=None,
        title=wav,
        cutoff=cutoff,
        order=lporder,
        acqfile=wav
    )
    #print(f'egg_display returned "{r}"')

@click.group()
def cli():
    pass

@cli.command()
@click.option('--spkr', callback=validate_ident, help='Three-letter speaker identifier')
@click.option('--lang', callback=validate_ident, help='Three-letter language identifier (ISO 639-3)')
@click.option('--researcher', callback=validate_ident, help='Three-letter researcher (linguist) identifier')
@click.option('--item', help='Representation of the stimulus item')
@click.option('--utt', required=False, default='', help='Utterance metadata (optional)')
@click.option('--seconds', required=False, default='', help='Acquisition duration (optional)')
@click.option('--autozero', required=False, default='0', type=int, help='Remove mean from display using _zero_ token # (optional)')
@click.option('--flow', is_flag=True, help='Turn on airflow channels')
@click.option('--pressure', is_flag=True, help='Turn on pressure channel')
@click.option('--lx', is_flag=True, help='Turn on LX (EGG) channel')
@click.option('--no-disp', is_flag=True, help='Skip display after acquisition')
@click.option('--cutoff', required=False, default=50, help='Lowpass filter cutoff in Hz (optional; default 50)')
@click.option('--lporder', required=False, default=3, help='Lowpass filter order (optional; default 3)')
@click.option('--device', required=False, default='2', help='EGG-D800/VoiceLab8 device version (optional; default 2)')
def acq(spkr, lang, researcher, item, utt, seconds, autozero, flow, pressure, lx, no_disp, cutoff, lporder, device):
    '''
    Make a recording.
    '''
    today = dt.today()
    todaystamp = dt.strftime(today, '%Y%m%d')
    tstamp = dt.strftime(today, '%Y%m%dT%H%M%S')
    sessdir = os.path.join(datadir, lang, spkr, todaystamp)
    Path(sessdir).mkdir(parents=True, exist_ok=True)
    token, fpath, inifile = get_fpath(
        sessdir, lang, spkr, researcher, tstamp, item, token=None
    )
    ini = get_ini(flow, pressure, lx, spkr, item, token, utt, device)
    with open(inifile, 'w') as out:
        out.write(ini)
    run_acq(fpath, inifile, seconds)

    if device == '1':
        chan = [
            'audio',
            'lx' if lx is True else None,
            'orfl' if flow is True else None,
            'nsfl' if flow is True else None
        ]
    else:
        chan = [
            'audio',
            'lx' if lx is True else None,
            'oralf' if flow is True else None,
            'oralp' if pressure is True else None,
            'nsfl' if flow is True else None
        ]
    chan =[c for c in chan if c is not None]
    print(chan)

    if item == '_zero_':
        stash_chanmeans(
            fpath,
            chan=chan,
            token=token,
            sessdir=sessdir,
            lang=lang,
            spkr=spkr,
            researcher=researcher,
            today=todaystamp
        )
    if no_disp is False:
        if autozero >= 0 and item != '_zero_':
            sessmd = load_sess_yaml(
                sessdir, lang=lang, spkr=spkr, today=todaystamp
            )
            chanmeans = []
            for a in sessmd['acq']:
                if a['item'] == '_zero_' and a['token'] == autozero:
                    chanmeans = np.zeros(len(a['channels']))
                    for c in a['channels']:
                        if c['type'] in ('orfl', 'nsfl'):
                            chanmeans[c['idx']] = c['mean']
                    break
            if len(chanmeans) == 0:
                print(f"Didn't find _zero_ token {autozero} for the current session!")
        else:
            chanmeans = [] # No adjustment
        wav_display(
            fpath,
            chan=chan,
            cutoff=cutoff,
            lporder=lporder,
            chanmeans=chanmeans
        )

@cli.command()
@click.option('--wavfile', required=False, default=None, help="Input .wav file")
@click.option('--spkr', help='Three-letter speaker identifier')
@click.option('--lang', help='Three-letter language identifier (ISO 639-3)')
@click.option('--researcher', help='Three-letter researcher (linguist) identifier')
@click.option('--item', help='Representation of the stimulus item')
@click.option('--date', required=False, default='today', help="YYYYMMDD session date")
@click.option('--token', type=int, required=False, default=-1, help="Token identifier (optional; defaults to last token)")
@click.option('--autozero', required=False, default='0', type=int, help='Remove mean from display using _zero_ token (optional)')
@click.option('--flow', is_flag=True, help='Turn on airflow channels')
@click.option('--pressure', is_flag=True, help='Turn on pressure channel')
@click.option('--lx', is_flag=True, help='Turn on LX (EGG) channel')
@click.option('--cutoff', required=False, default=50, help='Lowpass filter cutoff in Hz (optional; default 50)')
@click.option('--lporder', required=False, default=3, help='Lowpass filter order (optional; default 3)')
@click.option('--device', required=False, default='2', help='EGG-D800 device version (optional; default 2)')
def disp(wavfile, spkr, lang, researcher, item, date, token, autozero, flow,
    pressure, lx, cutoff, lporder, device):
    '''
    Display an eggd800 wavfile recording. If given, the --wavfile parameter
    identifies the .wav file to display. Otherwise, the name is constructed
    from the other parameters in a way that matches the acq() parameters.

    The --token parameter is used to specify the token identifier.
    Use negative values to count tokens in reverse: -1 for last token,
    -2 for second-to-last, and so on.

    The --autozero parameter is used to specify which _zero_ token from the
    acquisition session to use for calculating the channel means. Use the
    value -1 to indicate that the display should not be adjusted by the
    channel means.
    '''
    if wavfile is not None:
        sessdir = Path(wavfile).parent
    else:
        if date == 'today':
            date = dt.strftime(dt.today(), '%Y%m%d')
        sessdir = os.path.join(datadir, lang, spkr, date)
        tokgl = '*' if token < 1 else token
        wavfiles, fpat = find_wav(
            sessdir, lang, spkr, researcher, date, item, tokgl
        )
        if len(wavfiles) == 0:
            print(f'Could not find a matching .wav file matching {fpat}.')
            exit(0)
        elif len(wavfiles) > 1 and tokgl == '*':
            try:
                wavfile = wavfiles[token]
            except IndexError:
                print(f'Could not find matching file with token index {token}.')
                exit(0)
        elif len(wavfiles) > 1:
            print('Multiple matching files found. Use the --wavfile param and '
                  'specify one of:\n')
            print('\n'.join(wavfiles))
            exit(0)
        else:
            wavfile = wavfiles[0]
    if device == '1':
        chan = [
            'audio',
            'lx' if lx is True else None,
            'orfl' if flow is True else None,
            'nsfl' if flow is True else None
        ]
    else:
        chan = [
            'audio',
            'lx' if lx is True else None,
            'oralf' if flow is True else None,
            'oralp' if pressure is True else None,
            'nsfl' if flow is True else None
        ]
    chan =[c for c in chan if c is not None]

    if autozero >= 0:
        sessmd = load_sess_yaml(sessdir, lang=lang, spkr=spkr, today=date)
        chanmeans = []
        for a in sessmd['acq']:
            if a['item'] == '_zero_' and a['token'] == autozero:
                chanmeans = np.zeros(len(a['channels']))
                for c in a['channels']:
                    if c['type'] in ('orfl', 'nsfl'):
                        chanmeans[c['idx']] = c['mean']
                break
        if len(chanmeans) == 0:
            print(f"Didn't find _zero_ token {autozero} for the session!")
    else:
        chanmeans = [] # No adjustment
    wav_display(
        wavfile,
        chan=chan,
        cutoff=cutoff,
        lporder=lporder,
        chanmeans=chanmeans
    )

def check_chans(row, datadir, rolldir, device):
    '''
    Diagnose .wav file for incorrect channel order. Use `np.roll` to rotate
    the channels and save to `rolldir` where necessary.

    **NOTE** The current implementation is very simple and assumes that there
    are four channels, of which one is an empty EGG signal and which is
    expected to have lowest intensity.
    '''
    rate, d = scipy.io.wavfile.read(datadir / row.relpath / row.fname)
    # If recording is not a four-channel recording we don't know what to do with it.
    assert(d.shape[1] == 4)
    centered = d - d.mean(axis=0)

    # Calculation of zero crossings.
#    zc_rate = np.count_nonzero(
#        np.diff(centered > 0, axis=0),
#        axis=0
#    ) / (d.shape[0] / rate)
#    zcmax = np.argmax(
#        np.count_nonzero(
#            np.diff(centered > 0, axis=0),
#            axis=0
#        )
#    )

    # EGG channel normally not active and should have smallest amplitude overall.
    rms = np.sqrt(np.mean(centered ** 2, axis=0))
    # Channel order =
    # 'v1': ['audio', 'egg', 'orfl', 'nsfl'],
    # 'v2': ['audio', 'orfl', 'egg', 'nsfl']
    expectedidx = 1 if device == '1' else 2
    if rms.argmin() != expectedidx:
        rollname = rolldir / row.relpath / row.fname
        rollname.parent.mkdir(parents=True, exist_ok=True)
        scipy.io.wavfile.write(
            rollname, rate, np.roll(d, expectedidx - rms.argmin(), axis=1)
        )
        print(f'Rolled channels in {rollname}.')

@cli.command()
@click.option('--device', required=False, default='2', help='EGG-D800 device version (optional; default 2)')
def rollwav(device):
    '''
    Check all amznas .wav files for correct channel order. Make a corrected
    copy in 'rollwav' folder if channel order is incorrect.
    '''
    wavdir = Path(datadir)
    wavdf = dir2df(wavdir, fnpat=wavpat)
    rolldir = wavdir.parent / 'rollwav'
    if not rolldir.exists():
        rolldir.mkdir(parents=True, exist_ok=True)
    rolldf = dir2df(rolldir, fnpat=wavpat).loc[:, ['relpath', 'fname']]
    rolldf['rollexists'] = True
    todo = pd.merge(wavdf, rolldf, how='left', on=['relpath', 'fname'])
    todo = todo[(todo['item'] != '_zero_') & (todo['rollexists'].isna())]
    for row in todo.itertuples():
        check_chans(row, wavdir, rolldir, device=device)

if __name__ == '__main__':
    cli()
